### ISSUE TITLE
Import additional scss files from node_modules

### ISSUE THREAD

**Issue by philippbruhin** [noreading/bootstrap4-webpack-boilerplate#5]
First of all thank You Dominik for providing this great boilerplate.
I am trying to integrate [github.com/DesignRevision/shards-ui](https://github.com/DesignRevision/shards-ui) – but without success. May I ask if someone can reproduce my issue?

In a first step I add shards-ui via npm: `npm install --save shards-ui`

Then I update **src/index.js** as follows:

```javascript
// Remove the following lines, if you do not need any of Bootstrap's JavaScript features
import Popper from "popper.js";
window.jQuery = $;
window.$ = $;

require("bootstrap");
require("shards-ui");
```

Updating **src/scss/style.scss** as follows works without issues:

```scss
// This code does work and includes shards ui css
@import "~bootstrap/scss/bootstrap";
@import "~shards-ui/dist/css/shards.min.css";
```
But I am **not able to add shards scss** file from the **node_modules** folder:

```scss
// This code does not include shards ui scss
@import "~bootstrap/scss/bootstrap";
@import "~shards-ui/src/scss/shards";
```
May I ask if this behaviour is as expected? If so, any Idea how I can import shards-ui scss files?

**Comment by noreading** [comment]
Oooops! I didn't see the notification. :) It took only half year to react.

I tested it and in my case it works like expected. You can see in the attached screenshot, that the left side uses the SCSS version in `style.scss` and the compiled version on the right side (extracted in dev mode) includes the `Shards v.3.0.0` library.

Is this still an issue? If so, which operating system and node version are you using?

<img width="2560" alt="Bildschirmfoto 2020-05-08 um 17 03 44" src="https://user-images.githubusercontent.com/5540583/81419220-3328a600-914e-11ea-88d4-83a2816ecd7c.png">

**Comment by philippbruhin** [comment]
No worries. I tried again and now it is working with same setup (I think) as on that time. I am on Windows 10 with Node `v10.16.3`.

I cannot reproduce it anymore and I have no idea what went wrong at that time. So feel free to close this issue.

Thanks and have a nice weekend.

**Comment by noreading** [comment]
Have a nice weekend, too. :)
