### ISSUE TITLE
Images not created|recreated - even original example files

### ISSUE THREAD

**Issue by Seriousness** [noreading/bootstrap4-webpack-boilerplate#6]
Maybe I'm doing things wrong, but I really liked the advertised image features and was not able to create my own collection neither could recreate the "slider images 1" in the delivered example.

All collections say "no images found"

**Comment by noreading** [comment]
That sounds mysterious, but I'll have a look at it again next week.

**Comment by noreading** [comment]
Okay. It was easy, so I could do it a bit faster. :-)

The fix is done in the newest release [v.1.2.3](https://github.com/noreading/bootstrap4-webpack-boilerplate/releases/tag/v1.2.3).

**Comment by Seriousness** [comment]
Bless! Great!

**Comment by noreading** [comment]
Thanks for sharing it! Have a nice weekend. 👍
